function Hd = export_filter_coeffs
%EXPORT_FILTER_COEFFS Returns a discrete-time filter object.
%Filter Designed by Lt. Michael Ledford
%   MATLAB Code
%   Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
%   Generated on: 09-Apr-2016 20:09:38

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

N    = 40;       % Order
Fc   = 2500;     % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);
% Set the arithmetic property.
set(Hd, 'Arithmetic', 'fixed', ...
    'CoeffWordLength', 14, ...
    'CoeffAutoScale', false, ...
    'NumFracLength', 13, ...
    'Signed',         true, ...
    'InputWordLength', 16, ...
    'inputFracLength', 15, ...
    'FilterInternals',  'FullPrecision');
denormalize(Hd);


% [EOF]
